use bdportafolio;
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U005', 'LAURO ENCISO RODAS', 'lauro.enciso@unsaac.edu.pe', '$2b$12$VWwow1mb2H6MZELyYR5IlOKjjkU274/meQ1LP4mEyeWJ8BwGLRUj2');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U006', 'JULIO CÉSAR CARBAJAL LUNA', 'julio.césar@unsaac.edu.pe', '$2b$12$3bv5fHcQ8NrBlGxfC2CnaeLOgXn7Kmmirk19ndkNnWAswLaZQzCia');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U007', 'NILA ZONIA ACURIO USCA', 'nila.zonia@unsaac.edu.pe', '$2b$12$sPeEoUFtI5DTdYMXMId4qeBDnrl8FIoghOm.xmwrAArYr82Iinchi');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U008', 'JAVIER ARTURO ROZAS HUACHO', 'javier.arturo@unsaac.edu.pe', '$2b$12$Tmb1tkZbqJmB0gU1eUMMye6.HdJ/05ddi6sJ.tBqzXOxaxl/AnNHu');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U009', 'LINO PRISCILIANO FLORES PACHECO', 'lino.prisciliano@unsaac.edu.pe', '$2b$12$F7oR3LMUxlBVG8y/mW/i0Or4mNCYQdewWhHCKz8dRR4tkztw7tpxa');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U010', 'EDWIN CARRASCO POBLETE', 'edwin.carrasco@unsaac.edu.pe', '$2b$12$hoQAv9qmvspLGEfVNPfORe7buq1KwD0y1ZU902gqwcVdMIjBQaepa');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U011', 'EMILIO PALOMINO OLIVERA', 'emilio.palomino@unsaac.edu.pe', '$2b$12$qNnxzRcKfUVeZsdcaGYfMeHca12akm6Znq5MCZ09eqsvRid6Cd.4y');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U012', 'DENNIS IVÁN CANDIA OVIEDO', 'dennis.iván@unsaac.edu.pe', '$2b$12$PSk8HvA2LJP8zKVW03B4nuOnQKV5WpgZHPLOx1Dioy6P495k9EcXC');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U013', 'RONY VILLAFUERTE SERNA', 'rony.villafuerte@unsaac.edu.pe', '$2b$12$uVhYYX6LajfHYW7NydlZme7IEmWj81ticWB.LMNjZBGkFbxVCJES6');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U014', 'GUZMÁN TICONA PARI', 'guzmán.ticona@unsaac.edu.pe', '$2b$12$V3W9iR6ORt/4pTIs4QqhfurI5QB9hKKwEQFZTdpriuy2DwNnL6KZi');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U015', 'YESHICA ISELA ORMEÑO AYALA', 'yeshica.isela@unsaac.edu.pe', '$2b$12$1kebiYGKDGuWogbXxc9s6u83edUHasWCBunWhUylyyPQVGfqCnBE2');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U016', 'IVÁN CÉSAR MEDRANO VALENCIA', 'iván.césar@unsaac.edu.pe', '$2b$12$Oc8.E6c4uLZSqIdmlD8EMeJBNC5VbV5bMN15jjbnJfwUIKzvLBRci');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U017', 'LUIS BELTRÁN PALMA TTITO', 'luis.beltrán@unsaac.edu.pe', '$2b$12$T6Tm.epbfK5x3mQU9kaoTO2AUxZ6vpfiQziVdvDcnIsdfXh.Dgowq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U018', 'ROBERT WILBERT ALZAMORA PAREDES', 'robert.wilbert@unsaac.edu.pe', '$2b$12$fvFQyzzh/S2q1V5e5a/09Oi2sdcgVvTqIP.Eq707T24pEbrTio6LO');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U019', 'WALDO ELIO IBARRA ZAMBRANO', 'waldo.elio@unsaac.edu.pe', '$2b$12$m6I.4Nnjx4DLdU6BhIbc8Oh8fbIAujvFKEZkn.qtJaF.d9Q0.reem');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U020', 'KARELIA MEDINA MIRANDA', 'karelia.medina@unsaac.edu.pe', '$2b$12$f9.QUQyXPMi8rOEkgd652eLi6gWS8kyIXqAnX0na6evaUvEhua5Fq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U021', 'JAVIER DAVID CHÁVEZ CENTENO', 'javier.david@unsaac.edu.pe', '$2b$12$MW06B4ymZlLJOu18hyad4.uACZ60B8t.cRtI3hszRj5m.3f4swB2i');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U022', 'VANESSA MARIBEL CHOQUE SOTO', 'vanessa.maribel@unsaac.edu.pe', '$2b$12$u36hMn..NeXSYV476Y2IW.sJ0qXE8/gMLIVaGiGjFA7vSkS.uQn8q');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U023', 'MANUEL AURELIO PEÑALOZA FIGUEROA', 'manuel.aurelio@unsaac.edu.pe', '$2b$12$jwPMkD3h4ynPdRp1Pd1AIud/FDwb04q3GXYB0cEZLm9F3wIWPn9iq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U024', 'JOSÉ MAURO PILLCO QUISPE', 'josé.mauro@unsaac.edu.pe', '$2b$12$uqLkKr/r0STbOPJLhnzhZON6W.Z6v6zLrXWhvA/Rmfi..MHYRklMy');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U025', 'LINO AQUILES BACA CÁRDENAS', 'lino.aquiles@unsaac.edu.pe', '$2b$12$x7OGlcbfDqINzr0up506hOv6G9V/2kC36j7uFc4RdNQx5hWmsE4IW');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U026', 'ESTHER PACHECO VÁSQUEZ', 'esther.pacheco@unsaac.edu.pe', '$2b$12$A/U2CL0Gyuuh3lklj2w0BeLLbUKd/qFby2fFfcn3Jm5t0EAWP7HEK');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U027', 'WILLIAN ZAMALLOA PARO', 'willian.zamalloa@unsaac.edu.pe', '$2b$12$sN9IR/xh9W3aqdEbP7UF1.2hvR4.oKM01JQ1HF/E1mLN65azqz8mq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U028', 'HARLEY VERA OLIVERA', 'harley.vera@unsaac.edu.pe', '$2b$12$CVyJkEIxyGvzWWQeMph3B.3p89e7OzV9422la46ENGr0Q1EiUTnQK');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U029', 'MARITZA KATHERINE IRPANOCA CUSIMAYTA', 'maritza.katherine@unsaac.edu.pe', '$2b$12$dBAOpUHoKiN51Nlz.7MBq.ZkloxC8FFyWqQ56XVtiUGck57uydTEe');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U030', 'EFRAINA GLADYS CUTIPA ARAPA', 'efraina.gladys@unsaac.edu.pe', '$2b$12$T72OcXTLECgBKn4JeawzOuKVir7ArZrItk0p9EXPUlTGvAXvOnMwC');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U031', 'DARIO FRANCISCO DUEÑAS BUSTINZA', 'dario.francisco@unsaac.edu.pe', '$2b$12$k5Ojex6c0YyH70mk7BjyrODMl79uVvh3a14bMXgFdryhH4d7mJQ.y');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U032', 'DORIS SABINA AGUIRRE CARBAJAL', 'doris.sabina@unsaac.edu.pe', '$2b$12$ol.yIc81NZinV5mTyU3E.eDW/kX2P2zJaBgZ1RStX15suTEpxAvh6');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U033', 'TANY VILLALBA VILLALBA', 'tany.villalba@unsaac.edu.pe', '$2b$12$xmLig4A/zBq28dzFyLGanudzDiP57jiZUKWcyVNhmEuvx1m8MOAWm');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U034', 'CARLOS FERNANDO MONTOYA CUBAS', 'carlos.fernando@unsaac.edu.pe', '$2b$12$VJLYXEfnQ9qqa0ePddNwn.3/8PEA2851RO1zj4zHBp4g65iOIMBvq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U035', 'CARLOS RAMÓN QUISPE ONOFRE', 'carlos.ramón@unsaac.edu.pe', '$2b$12$82UhuQM.mT0BHIXfgCS.3u6K0Ta2LQ4F/UryO.34BB2hx7vBSxoqO');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U036', 'BORIS CHULLO LLAVE', 'boris.chullo@unsaac.edu.pe', '$2b$12$M9MTVx44/4fHA9B.5b1Px.dP8IdNjkpj3I6TG4/M9jSEAnacnZfbW');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U037', 'HÉCTOR UGARTE ROJAS', 'héctor.ugarte@unsaac.edu.pe', '$2b$12$h8We0qR1I267U0n4hz4iKeq239pK3k9FKbW0s7M12ZcwXl9T0/MC6');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U038', 'LUIS ALVARO MONZON CONDORI', 'luis.alvaro@unsaac.edu.pe', '$2b$12$V4SnhBPDXNocRv0SAbEhb.0325OJXxzdfyYFoeTin1zR45a7Mfb0u');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U039', 'EDGAR QUISPE CCAPACCA', 'edgar.quispe@unsaac.edu.pe', '$2b$12$vzACkGNM3Q.oB9sDHTDsROyFgTPkewskLyyoh8ye6u3bJUbAI9VPG');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U040', 'ELIDA FALCON HUALLPA', 'elida.falcon@unsaac.edu.pe', '$2b$12$4jIItC3lXvI5S58BgZSLzuVEektsSae2PJDkvoqn4EHpCmtTGfsS6');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U041', 'VICTOR DARIO SOSA JAUREGUI', 'victor.dario@unsaac.edu.pe', '$2b$12$rF.ZUgyF2SW1teypfAqx0uqyIKopUsxpk1uBxeriZNVIhqIEfmdlG');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U042', 'JISBAJ GAMARRA SALAS', 'jisbaj.gamarra@unsaac.edu.pe', '$2b$12$14k11Vgwvz7.Qleij10LEe97hUgSKqp/7lU3ehQ.Bd8qgId.2Zhai');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U043', 'HENRY SAMUEL DUEÑAS DE LA CRUZ', 'henry.samuel@unsaac.edu.pe', '$2b$12$6uXhgi1e1gXtNa/omGnhp.s28rdMvQKHPpNWPqgk0MOZfI533sBbK');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U044', 'RAUL HUILLCA HUALLPARIMACHI', 'raul.huillca@unsaac.edu.pe', '$2b$12$yFM3pE/j8S21oCuLQ9PlAu2Y9YDSMyV6qaza/j6wyzgWmQZL9YOf2');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U045', 'GERAR FRANCIS QUISPE TORRES', 'gerar.francis@unsaac.edu.pe', '$2b$12$e35No7TNWgBcQtfw8Y.8p.tC/BfxMFb9T3li6UeqpDGvZ0pE.JPSa');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U046', 'MARCIO FERNANDO MERMA QUISPE', 'marcio.fernando@unsaac.edu.pe', '$2b$12$eSG6rULiTxaD82xL6xq5LunTE7BZ8ehdgKvjio83VI45Br.RQQ02m');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U047', 'VANESA LAVILLA ALVAREZ', 'vanesa.lavilla@unsaac.edu.pe', '$2b$12$P.to4snNu3ng2u4ZUDbRuudzB7v4qyc3H5FRhWIyGkIxHawIL7bN.');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U048', 'SHIRLEY RUTH VELAZQUE ROJAS', 'shirley.ruth@unsaac.edu.pe', '$2b$12$rXofPVKYDI0wZTbM6ynige7xubgMQhf.N8B2.5k5HgGJHn08Beeiu');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U049', 'JOSE GUILLERMO ANDRADE CARI', 'jose.guillermo@unsaac.edu.pe', '$2b$12$cR5fbK7CPMmvCD.wTbtTvO1ztK7vDMgQOG.CHcbkXf2EI/JRjudKG');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U050', 'HANSH HARLEY CCACYAHUILLCA BÉJAR', 'hansh.harley@unsaac.edu.pe', '$2b$12$duB7FX3UgHroZHayjepTCuxSsMJlKVIvisa6B5haYiHKCL9nNV6PC');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U051', 'LISHA SABAH DIAZ CACERES', 'lisha.sabah@unsaac.edu.pe', '$2b$12$SrLyweuqijLZlZ50nyKhSO4GweGf6nWWeQ33PeivHl.xi2oqEtQ6m');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U052', 'STEPHAN JHOEL COSIO LOAIZA', 'stephan.jhoel@unsaac.edu.pe', '$2b$12$WHAPVP5Iak6OBl86hDgEaOgyFUW3p6e/blg4UUBkym/mkF5xvC8Wa');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U053', 'RAY DUEÑAS JIMENEZ', 'ray.dueñas@unsaac.edu.pe', '$2b$12$uvJmqj1LMkqfVltrT.zUyemtbA/NaiCIpesdli.JY4chUNuNni9vi');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U054', 'GABRIELA ZUÑIGA ROJAS', 'gabriela.zuñiga@unsaac.edu.pe', '$2b$12$AJutsFlU1Pz19oFsWc6BYe5A5zuSt/kEx36dHHhCM2otlt/Dva.X2');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U055', 'RAIMAR ABARCA MORA', 'raimar.abarca@unsaac.edu.pe', '$2b$12$u9nFxA0YDKGYr0pdBkJdlOU08FwoOBGPabnYe56yGud7YXS1L7pYG');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U056', 'LUZ INDIRA GUZMAN FELIX', 'luz.indira@unsaac.edu.pe', '$2b$12$8QZjsBM0l3wYjTCGjlvDCefVPGR48P4rNCy9zUJCL/ukMXa7Mc5eC');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U057', 'CLAUDIA FRANCESCA SUAREZ', 'claudia.francesca@unsaac.edu.pe', '$2b$12$x/5OLjKya1uLrAUKppY7AeUp02Ye/nhzWxT9dbhm9.vxSzbMj4yq2');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U058', 'MARÍA DEL PILAR VENEGAS VERGARA', 'maría.del@unsaac.edu.pe', '$2b$12$3FDGcY817vyD6dHWDH26jOP3bx0ioKHaoz2nOkoF1Mm0AnLCiy5q6');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U059', 'AGUEDO HUAMANI HUAYHUA', 'aguedo.huamani@unsaac.edu.pe', '$2b$12$yiMMpocY5.JsmMvryTrIG.cgj5zvUPAEpLIeqblzUjs/itcPueeEi');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U060', 'OLMER CLAUDIO VILLENA LEÓN', 'olmer.claudio@unsaac.edu.pe', '$2b$12$h.nC4XfsXFLTo6NWBqf5GOFjuFgT1fcqrnHxfKjMVVqhKaeReoSvq');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U061', 'JONEL CCENTE ZUZUNAGA', 'jonel.ccente@unsaac.edu.pe', '$2b$12$IgpO5Gmc4iKaL2ENjQzoeO5NYuIWOd.6ymqT.kd.OZILllNnYtxQu');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U062', 'VICTOR GABRIEL JALISTO', 'victor.gabriel@unsaac.edu.pe', '$2b$12$wzPbds0MJ9tTWeQ0/GcQ7OeDjuLe6d8fMIbLKlY86lldyE3BRrDnm');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U063', 'ALEX FERNANDO HUILLCA HUAMAN', 'alex.fernando@unsaac.edu.pe', '$2b$12$oH.ZayQrkhqkVyRzoy6kVOd/M7qYN5C6Pf5ORBkUlhtcImBAag01O');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U064', 'NOHELY LISSETH OCHOA HUAYHUA', 'nohely.lisseth@unsaac.edu.pe', '$2b$12$qh6/.pficWHa3RKQyaTrQu5j5StjZ/iMiEC1kkDDaDzTR3jdWLBYS');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U065', 'ALFREDO COLLANTES MENDOZA', 'alfredo.collantes@unsaac.edu.pe', '$2b$12$fmwIymrwO2lwJyEZBxPyeOPZ4v7tutfA8hX/1KgjBZn7qQxsTDJWO');
INSERT INTO TUsuario (id_usuario, Nombre, email, password) VALUES ('U066', 'ELMER CAMA CACERES', 'elmer.cama@unsaac.edu.pe', '$2b$12$wQOmMWAqaOIdJWntSN1PJeTJmwvCZCZLHBW.zdygEXZKN2EY56EAG');
